version: "3"

services:
  web:
    build: nodejs
    ports:
      - 80:3000
      - 443:443
    depends_on:
      - db
 
  db:
    image: mariadb:latest
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass
    
